name = "Hi"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "Hi_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "Hi.wasm"
command = "npm run build:release"
